# Generated by Django 3.1.2 on 2020-11-19 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_content_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.CharField(default='slug', max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='content',
            name='pages',
        ),
        migrations.AddField(
            model_name='content',
            name='slug',
            field=models.CharField(default='slug', max_length=256),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(default='Product features'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=True, help_text='Check if featured', verbose_name='Featured product?'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(default='slug', max_length=256),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(default='Title', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Product name', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.category'),
        ),
    ]
