# Generated by Django 3.1.2 on 2020-11-21 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data',
            table='Graph_table',
        ),
    ]
